### ISSUE TITLE
Getting waitForImages

### ISSUE THREAD

**Issue by alexanderdickson** [intersel/iFSMAnimation#1]
Hi. 

I see you're loading the waitForImages from Github's raw content. I'm not sure if it's supposed to be used as a CDN like that.

You could add waitForImages as a dependency via Bower. That way when people use your script, they don't need to fire off an additional XHR (waitForImages will be bundled with your code).

**Comment by intersel** [comment]
Hi Alexander
You're right... should change that... My initial idea was to download all the external needed librairies without knowing anything in javascript... and that was a try to see how to do that...
I'll take a look on bower that I don't know..
Thanks,

**Comment by intersel** [comment]
Not calling the waitForImages from github anymore...
waitForImages is proposed as an external lib.
